### ISSUE TITLE
possible bug in compileCmdContent

### ISSUE THREAD

**Issue by tiarno** [janbrohl/SimpleTAL#3]
hi, I've been working on a python3 version of simpletal and came across this in my code. I'm pretty sure this is a bug: https://github.com/janbrohl/SimpleTAL/blob/python2and3/lib/simpletal/simpleTAL.py#L1233

On a `tal:content` attribute, the flag 'structure' should not escape the expression and the flag 'text' should escape the expression. The attProps[1] should be attProps[0]. That works for my own code.

**Comment by janbrohl** [comment]
Thank you for reporting. Obviously there are not enough tests yet. It would be great if you could submit code producing an error with this or a full test case.

**Comment by janbrohl** [comment]
Fixed in 247e736c3c33ae6b7cf9e901f0297b74cdfafeef

**Comment by tiarno** [comment]
thanks for that quick response.
